# Generated by Django 2.0.5 on 2018-05-20 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data', models.DateField(blank=True)),
                ('hora_inicio', models.TimeField(blank=True)),
                ('hora_final', models.TimeField(blank=True)),
                ('paciente', models.CharField(blank=True, default='', max_length=100)),
                ('procedimento', models.CharField(choices=[('consulta', 'CONSULTA'), ('retorno', 'RETORNO'), ('horario bloqueado', 'HORARIO BLOQUEADO')], default='consulta', max_length=17)),
                ('highlighted', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
