# Generated by Django 2.0.5 on 2018-05-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iclinicapp', '0002_auto_20180521_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='highlighted',
        ),
    ]
