# Generated by Django 2.0.5 on 2018-05-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iclinicapp', '0002_auto_20180518_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='code',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='language',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='linenos',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='style',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='title',
        ),
    ]
