# Generated by Django 2.0.5 on 2018-05-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iclinicapp', '0003_auto_20180518_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
